language: java
jdk:
  - oraclejdk8
before_install:
  - wget http://services.gradle.org/distributions/gradle-3.5-bin.zip
  - unzip -qq gradle-3.5-bin.zip
  - export GRADLE_HOME=$PWD/gradle-3.5
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v
  - nvm install 6.9.1
  - cd ./generator-liberty
  - npm i -g makeshift && makeshift -r https://registry.npmjs.org
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run testint
  - npm run coveralls
  - ../deploy.sh
